-- 코드를 입력하세요
WITH CART AS(
    SELECT CART_ID, GROUP_CONCAT(NAME SEPARATOR ', ') AS PRODUCTS
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) 
SELECT CART_ID
FROM CART
WHERE (PRODUCTS LIKE "%Milk%") AND (PRODUCTS LIKE "%Yogurt%")
ORDER BY CART_ID ASC;