WITH FIR AS (
    SELECT ID AS FIR_ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SEC AS (
    SELECT ID AS SEC_ID 
    FROM ECOLI_DATA E, FIR F
    WHERE E.PARENT_ID = F.FIR_ID
)
SELECT ID 
FROM ECOLI_DATA E, SEC S
WHERE E.PARENT_ID = S.SEC_ID
ORDER BY ID ASC;

