-- 코드를 입력하세요
WITH SALES AS (
    SELECT ONLINE_SALE_ID AS ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE, USER_ID FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID AS ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE, NULL AS USER_ID FROM OFFLINE_SALE
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM SALES
WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC

