# -- 코드를 입력하세요
SELECT P.CATEGORY, P.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY
) AS P ON F.CATEGORY = P.CATEGORY
WHERE (P.CATEGORY LIKE "식용유" OR P.CATEGORY LIKE "국" OR P.CATEGORY LIKE "김치" OR P.CATEGORY LIKE "과자")
AND F.PRICE = P.MAX_PRICE
ORDER BY P.MAX_PRICE DESC;
# select * from food_product;